<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="SnipBasicValidatorTests.cs" />
    <Compile Remove="UnitTest2.cs" />
    <Compile Remove="ValidationRunnerTests.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Core" Version="4.0.100" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.100" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.100" />
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="EdiFabric" Version="10.7.6" />
    <PackageReference Include="EdiFabric.Templates.Edifact" Version="2.7.6" />
    <PackageReference Include="EdiFabric.Templates.Hipaa" Version="2.7.7" />
    <PackageReference Include="EdiFabric.Templates.X12" Version="2.7.6" />
    <PackageReference Include="EntityFramework" Version="6.5.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="8.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="8.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Moq.EntityFrameworkCore" Version="8.0.0.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EDI275AttachmentParser\EDI275AttachmentParser.csproj" />
  </ItemGroup>

</Project>
